services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    environment:
      AUTH_SECRET: "${AUTH_SECRET}"
      AUTH_42_SCHOOL_ID: "${AUTH_42_SCHOOL_ID}"
      AUTH_42_SCHOOL_SECRET: "${AUTH_42_SCHOOL_SECRET}"
