name: Prettier

on:
  push:
    paths-ignore:
      - 'assets/**'
      - 'README.md'

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npx prettier --check ./src
