name: Tests

on:
  push:
    paths-ignore:
      - 'assets/**'
      - 'README.md'
      - 'LICENSE.md'
      - 'docs/**'
      - 'scripts/**'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Jest
      run: npx jest
